#! /bin/sh
# Make a .web file to extract the module definition from a .hweb file.
input=$1
output=$2
(
cat <<EOF
@* Module definition.  Automatically generated by makemodule.
@I macros.hweb
@I `basename $input`
@ Here is the module definition.
@a
EOF
for m in `grep package_end $input | sed -e 's/.*(//' -e 's/).*//' | grep -v '^pk$'`;do
echo "      "${m}_module
done
) > $output
exit 0
